/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 neon_sun_moon.glb 
Author: Godless Laboratories (https://sketchfab.com/noelnoir)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/neon-sun-moon-a0d6ad76fa4f494f82a8e92b8c1493a4
Title: Neon Sun & Moon
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Neon_sun_moon(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/neon_sun_moon.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.042}>
          <group name="9a67b9a4bcf644848035c7cd06720216fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Neon_Sun_&_Moon_1_arm" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_19" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_21" position={[-6000, 3000, 0]} rotation={[0, 0, 0.305]} scale={1200} />
                    <group name="Object_23" position={[5999.999, 3000, 0]} rotation={[-Math.PI, 0, 2.836]} scale={1500} />
                    <group name="Object_25" position={[-4999.999, 3000, 0]} rotation={[0, 0, -0.436]} scale={1200} />
                    <group name="Object_27" position={[4999.999, 2900, 0]} rotation={[Math.PI, 0, 1.92]} scale={1500} />
                    <skinnedMesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials['neon.sun1']} skeleton={nodes.Object_22.skeleton} morphTargetDictionary={nodes.Object_22.morphTargetDictionary} morphTargetInfluences={nodes.Object_22.morphTargetInfluences} />
                    <skinnedMesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials['neon.moon1']} skeleton={nodes.Object_24.skeleton} morphTargetDictionary={nodes.Object_24.morphTargetDictionary} morphTargetInfluences={nodes.Object_24.morphTargetInfluences} />
                    <skinnedMesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials['neon.sun2']} skeleton={nodes.Object_26.skeleton} morphTargetDictionary={nodes.Object_26.morphTargetDictionary} morphTargetInfluences={nodes.Object_26.morphTargetInfluences} />
                    <skinnedMesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials['neon.moon2']} skeleton={nodes.Object_28.skeleton} morphTargetDictionary={nodes.Object_28.morphTargetDictionary} morphTargetInfluences={nodes.Object_28.morphTargetInfluences} />
                    <skinnedMesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.darkwall} skeleton={nodes.Object_20.skeleton} />
                  </group>
                </group>
                <group name="wall" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="sun1circle" position={[-6000, 3000, 0]} rotation={[0, 0, 0.305]} scale={1200} />
                <group name="moon1curve1" position={[5999.999, 3000, 0]} rotation={[-Math.PI, 0, 2.836]} scale={1500} />
                <group name="sun1circle002" position={[-5000, 3000, 0]} rotation={[0, 0, -0.436]} scale={1200} />
                <group name="moon1curve1002" position={[4999.999, 2900, 0]} rotation={[Math.PI, 0, 1.92]} scale={1500} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/neon_sun_moon.glb')
